# 기본 실험 파라미터
base_params:
  dataset: "agnews"
  n_clusters: null
  skip_gae: true  # GAE는 스킵하고 Proposed GAE만 테스트
  embeddings:
    tfidf:
      method: "threshold"
      max_features: null
      threshold: 0.9
    pretrained:
      text_model: "BAAI/bge-large-en-v1.5"
      text_model_type: "sentence_transformer"
      image_model: "google/vit-base-patch16-224-in21k"
  graph:
    method: "reranked_tfidf_text"
    alpha: 0.2
    max_connections: 20
    omega: 0.5

# 실험할 하이퍼파라미터 조합 (최소화)
experiments:
  gae:
    enabled: false  # GAE 실험 비활성화

  proposed:
    enabled: true
    params:
      channels1: [256]
      channels2: [64]
      lr: [0.01]
      lambda_factor: [1.0]
      hard_negative_ratio: [0.5]
      k_hop_values: [[3, 4]]
    fixed_params:
      epochs: 1000
      eval_interval: 10
      early_stopping: 100
      use_scheduler: true
      use_standard_gae: false
      gae_init_feature: "combined"
      use_k_hop_negatives: true

  graph:
    enabled: true
    method: "reranked_tfidf_text"
    params:
      alpha: [0.2]
      max_connections: [20]
      omega: [0.25, 0.5, 0.75]

  embeddings:
    enabled: false  # 임베딩 실험 비활성화 